#!/usr/bin/env python3
"""Build a unified object manifest from YCB/HOPE inventory CSV files."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


def load_inventory(path: Path) -> dict[str, list[str]]:
    by_object: dict[str, list[str]] = defaultdict(list)
    if not path.exists():
        return by_object

    with path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            object_id = row.get("object_id", "").strip()
            mesh_path = row.get("mesh_path", "").strip()
            if object_id and mesh_path:
                by_object[object_id].append(mesh_path)

    return by_object


def entries_for(dataset: str, by_object: dict[str, list[str]]) -> list[dict[str, object]]:
    entries = []
    for object_id in sorted(by_object):
        mesh = sorted(by_object[object_id])[0]
        entries.append(
            {
                "dataset": dataset,
                "object_id": object_id,
                "display_name": object_id.replace("_", " "),
                "mesh_visual": mesh,
                "mesh_collision": mesh,
                "scale": 1.0,
                "units": "meters_assumed",
                "notes": "Autogenerated from inventory; verify scale/orientation before training.",
            }
        )
    return entries


def to_yaml(manifest: dict[str, object]) -> str:
    lines: list[str] = []
    lines.append("schema_version: 1")
    lines.append("generated_from:")
    gen = manifest["generated_from"]
    lines.append(f"  ycb_inventory: {gen['ycb_inventory']}")
    lines.append(f"  hope_inventory: {gen['hope_inventory']}")
    lines.append("objects:")

    objects = manifest["objects"]
    if not objects:
        lines.append("  []")
        return "\n".join(lines) + "\n"

    for obj in objects:
        lines.append(f"  - dataset: {obj['dataset']}")
        lines.append(f"    object_id: {obj['object_id']}")
        lines.append(f"    display_name: \"{obj['display_name']}\"")
        lines.append(f"    mesh_visual: {obj['mesh_visual']}")
        lines.append(f"    mesh_collision: {obj['mesh_collision']}")
        lines.append(f"    scale: {obj['scale']}")
        lines.append(f"    units: {obj['units']}")
        lines.append(f"    notes: \"{obj['notes']}\"")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ycb-inventory", default="data/objects/ycb/ycb_inventory.csv")
    parser.add_argument("--hope-inventory", default="data/objects/hope/hope_inventory.csv")
    parser.add_argument(
        "--out", default="data/objects/manifests/objects_manifest.yaml"
    )
    args = parser.parse_args()

    ycb = load_inventory(Path(args.ycb_inventory))
    hope = load_inventory(Path(args.hope_inventory))

    manifest = {
        "schema_version": 1,
        "generated_from": {
            "ycb_inventory": args.ycb_inventory,
            "hope_inventory": args.hope_inventory,
        },
        "objects": entries_for("ycb", ycb) + entries_for("hope", hope),
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(to_yaml(manifest), encoding="utf-8")

    print(f"Manifest objects: {len(manifest['objects'])}")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
