#!/usr/bin/env python3
"""Validate mesh files listed in an object manifest."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_manifest(path: Path) -> list[dict[str, str]]:
    """Very small parser for the manifest YAML format generated by build_object_manifest.py."""
    objects: list[dict[str, str]] = []
    current: dict[str, str] | None = None

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        if line.startswith("  - "):
            if current:
                objects.append(current)
            current = {}
            key, value = line[4:].split(":", 1)
            current[key.strip()] = value.strip().strip('"')
            continue

        if current and line.startswith("    ") and ":" in line:
            key, value = line.strip().split(":", 1)
            current[key.strip()] = value.strip().strip('"')

    if current:
        objects.append(current)

    return objects


def load_with_trimesh(mesh_path: Path) -> tuple[bool, str]:
    try:
        import trimesh  # type: ignore
    except ImportError:
        return True, "skipped geometry parse (trimesh not installed)"

    try:
        mesh = trimesh.load(mesh_path, force="mesh")
        if mesh is None:
            return False, "trimesh returned None"
        return True, "ok"
    except Exception as exc:  # noqa: BLE001
        return False, f"load error: {exc}"


def check_mesh(path: Path) -> tuple[bool, str]:
    if not path.exists():
        return False, "missing file"
    return load_with_trimesh(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest", default="data/objects/manifests/objects_manifest.yaml"
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        raise SystemExit(f"Manifest not found: {manifest_path}")

    objects = parse_manifest(manifest_path)
    total_refs = 0
    failed = 0

    for entry in objects:
        object_id = entry.get("object_id", "unknown")
        for field in ("mesh_visual", "mesh_collision"):
            total_refs += 1
            mesh_path = Path(entry.get(field, ""))
            ok, msg = check_mesh(mesh_path)
            if not ok:
                failed += 1
                print(f"FAIL {object_id} {field}: {mesh_path} ({msg})")

    print(f"Checked mesh references: {total_refs}")
    print(f"Pass: {total_refs - failed}")
    print(f"Fail: {failed}")

    if failed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
